### ISSUE TITLE
Improve Mobile Navigation

### ISSUE THREAD

**Issue by marcoroth** [marcoroth/hotwire.io#12]
Right now the navigation on mobile devices doesn't collapse into a Hamburger-like menu, which would be better suited for small screens

**Comment by pkayokay** [comment]
Would love to take this one too :)

**Comment by marcoroth** [comment]
I think @SmithWebDev started with this one. 

@SmithWebDev if you are still working on it, can you please comment on this issue so I can assign it to you?

**Comment by SmithWebDev** [comment]
Absolutely
