### ISSUE TITLE
Tom Select is not actively maintained.

### ISSUE THREAD

**Issue by ascruggs** [marcoroth/hotwire.io#13]
It has been almost a year since it was last updated.  
Its a shame, because it was a great library.  
Choices.js is the best alternative I've found.

**Comment by marcoroth** [comment]
Tom Select is still the one of most complete and best ones out there, which is why I'd still recommend that one.

Choices.js hasn't been updated in over a year though, last commit on Tom Select was "only" 10 months ago

**Comment by marcoroth** [comment]
Tom Select just got a new release: https://github.com/orchidjs/tom-select/releases/tag/v2.3.0
