### ISSUE TITLE
RubyMine 2024.2 supports Stimulus 

### ISSUE THREAD

**Issue by DmitryPogrebnoy** [marcoroth/hotwire.io#273]
There is a new RubyMine version (2024.2) with Stimulus support.
Please make a notion about it here - https://github.com/marcoroth/hotwire.io/blob/main/app/content/pages/ecosystem/tooling/stimulus-lsp/install/rubymine.html.erb

**Comment by marcoroth** [comment]
Hey @DmitryPogrebnoy, thanks for opening the issue!

Are you using RubyMine, if so, would you mind opening a pull request?

**Comment by DmitryPogrebnoy** [comment]
Thank you for the quick response! Sure, will open a pull request

**Comment by DmitryPogrebnoy** [comment]
Here is a PR - https://github.com/marcoroth/hotwire.io/pull/274

**Comment by marcoroth** [comment]
Resolves with #274, thanks!
