### ISSUE TITLE
Improve Frameworks page

### ISSUE THREAD

**Issue by marcoroth** [marcoroth/hotwire.io#33]
Right now the frameworks page is pretty barebones and empty.

<img width="1183" alt="CleanShot 2023-10-15 at 16 12 35@2x" src="https://github.com/marcoroth/hotwire.io/assets/6411752/a6d1124e-50f7-4f10-bba9-09f2c9c41940">

Pages like Tailwind make them feel more alive and vibrant.
https://tailwindcss.com/docs/installation/framework-guides

We should also aim for something like this on Hotwire.io

**Comment by pkayokay** [comment]
Can I take this one?

**Comment by marcoroth** [comment]
@pkayokay sure thing 🙌🏼
