### ISSUE TITLE
Something's off. Most of the links on the website lead to: Apologies, but this page hasn't been created yet.

### ISSUE THREAD

**Issue by vfonic** [marcoroth/hotwire.io#332]
I just discovered https://hotwire.io/ and tried to click around to see what's it all about. But most of the pages take me to:

> Apologies, but this page hasn't been created yet.

For example: https://hotwire.io/documentation

5 out of 8 links on that page lead to 404.

I've seen similar just clicking around the rest of the website links such as footer links.

**Comment by marcoroth** [comment]
Hey @vfonic, most of the pages aren't created yet, as the page suggests. It's a lot of effort to write and coordinate documentation. The idea is that this website is sort of seen as a Wiki, so the community can write documentation and best practices together. If you have some ideas or want to write the content for some of these pages it'd be more than welcome!

**Comment by vfonic** [comment]
Ah got it! It's a work-in-progress. I assumed that something with the link generation was broken.
