### ISSUE TITLE
Add link of Hotwire Weekly RSS feed to newsletter page

### ISSUE THREAD

**Issue by marcoroth** [marcoroth/hotwire.io#34]
It would be great to have a link to the RSS feed (https://buttondown.email/hotwireweekly/rss) and the newsletter archive (https://buttondown.email/hotwireweekly/archive/) on the https://hotwire.io/newsletter page.

Here's a screenshot of how it's being done on https://buttondown.email/hotwireweekly:

<img width="792" alt="CleanShot 2023-10-16 at 01 06 07@2x" src="https://github.com/marcoroth/hotwire.io/assets/6411752/662dd492-c509-4de0-865c-8e9e6ced10ec">

**Comment by joancodes** [comment]
Commenting on this to get assigned 😀

**Comment by marcoroth** [comment]
Thanks @joancodes, it's yours!
