### ISSUE TITLE
Share link returns 500 "This Edge Function has crashed."

### ISSUE THREAD

**Issue by ansonhoyt** [marcoroth/hotwire.io#35]
You likely have some automated error notifications, but just in case...

After successfully subscribing, I tried the "Email" share link, which took me to a 500 response at `https://share.bingo/email?url=https%3A%2F%2Fbuttondown.email%2Fhotwireweekly&text=I%20just%20subscribed%20to%20Hotwire%20Weekly!`

Body included:
```
500: INTERNAL_SERVER_ERROR
Code: EDGE_FUNCTION_INVOCATION_FAILED
ID: iad1::rt45f-1697476217194-dfa5de906c9b
```

Looking forward to the newsletters ❤️

**Comment by marcoroth** [comment]
Thanks @ansonhoyt, I'm using Buttondown to manage the newsletter and it looks like Buttondown uses the `share.bingo` service to handle the share links 😅 

I'll let them know and reference this issue, thank you!
