### ISSUE TITLE
Implement breadcrumbs for better navigation

### ISSUE THREAD

**Issue by marcoroth** [marcoroth/hotwire.io#36]
Currently when you navigate from something like the use-cases section... 

<img width="1167" alt="CleanShot 2023-10-16 at 20 38 35@2x" src="https://github.com/marcoroth/hotwire.io/assets/6411752/0c1b3400-8a77-4c88-a3c7-6b4824571159">

... to a sub-page you basically loose the context of where you are:

<img width="1171" alt="CleanShot 2023-10-16 at 20 39 01@2x" src="https://github.com/marcoroth/hotwire.io/assets/6411752/5d3b7583-2269-45c0-8ec5-78866b14dfdf">

It would be great if we could somehow indicate that a specific subpage is part of the bigger section of the website.

**Comment by divagueame** [comment]
Hi Marco,
I made this PR https://github.com/marcoroth/hotwire.io/pull/45 to add breadcrumbs. They would look this is:
![image](https://github.com/marcoroth/hotwire.io/assets/54085409/cd4d75bb-311a-4695-b06c-4cc17eaca773)

**Comment by marcoroth** [comment]
Done via #45/#46
