### ISSUE TITLE
Touch up README with a "Getting Started" and "Running locally" section

### ISSUE THREAD

**Issue by marcoroth** [marcoroth/hotwire.io#43]
In order to help people get up and running with the project we should have a "Getting Started" and "Running locally" section in the README.

**Comment by divagueame** [comment]
Hi, this could be a start for this issue:
https://github.com/marcoroth/hotwire.io/pull/45

**Comment by shubhusion** [comment]
kindly assign this issue to me. I will do the PR asap.

**Comment by marcoroth** [comment]
@shubhusion we had a first version of this merged in #46, but I think a section for showing how the run the linters locally would also be helpful!

**Comment by shubhusion** [comment]
@marcoroth  #49

**Comment by marcoroth** [comment]
Resolved via #46 and #49
