### ISSUE TITLE
Add and setup `sitemap_generator` gem

### ISSUE THREAD

**Issue by marcoroth** [marcoroth/hotwire.io#47]
For SEO purposes it would make sense to also provide a sitemap with all the subpages we have, so the search engine can better index and navigate the content on our site.

**Comment by joancodes** [comment]
Hi @marcoroth. I can look at this!

**Comment by marcoroth** [comment]
Awesome, thanks @joancodes! Let me know if you need any details 🙌🏼

**Comment by joancodes** [comment]
Is the following code snippet a reliable way to generate a sitemap that includes all the sub-pages with a preferred update frequency of 'weekly' and a high priority of 0.9 for each page?

```
PageModel.all.each do |page|
    add page_path(resource_path: page.request_path), changefreq: 'weekly', priority: 0.9
end
```

**Comment by marcoroth** [comment]
Yes, I think you can use `PageModel` for this! We probably just need the extra `root_url` since it's not captured by the `PageModel`.

I'm not sure if it really makes sense to have the same high priority for all the pages. Maybe we can do something clever to determine the priority based on the amount of levels the page is, something like:

```ruby
PageModel.all.each do |page|
  nest_level = page.request_path.split("/").count.to_f
  priority = nest_level.zero? ? 0.9 : (1 / nest_level)

  add page_path(resource_path: page.request_path), changefreq: 'weekly', priority: priority
end
```

**Comment by joancodes** [comment]
Awesome! This makes sense. Working on it.

**Comment by marcoroth** [comment]
Resolved via https://github.com/marcoroth/hotwire.io/pull/52
