### ISSUE TITLE
Implement Videos page

### ISSUE THREAD

**Issue by marcoroth** [marcoroth/hotwire.io#54]
Here's a rough mockup how such a page could look like:

![image](https://github.com/marcoroth/hotwire.io/assets/6411752/fd4051a7-9773-48e8-8fdc-269079e4eb1a)

**Comment by shubhusion** [comment]
Kindly assign this issue to me.

**Comment by marcoroth** [comment]
Just as a heads-up, there's probably quite some overlap design-wise with the issue https://github.com/marcoroth/hotwire.io/issues/53
