### ISSUE TITLE
Adding a link to Wagtail's usage of Stimulus 

### ISSUE THREAD

**Issue by lb-** [marcoroth/hotwire.io#57]
Great website! It looks incredible. 

I'd like to ask about if there would be a suitable place I link to Wagtail's first class support for Stimulus when building customisations into the CMS. It may be suitable for the framework integrations, but it's likely only Stimulus and not Turbo. 

### Suggestion

A 'framework' section under Python - with a page that links to the docs? A copy of https://github.com/marcoroth/hotwire.io/blob/main/app/content/pages/frameworks/django.html.erb essentially. 

Adding to this page I assume. https://hotwire.io/frameworks

If this is the appropriate place, I'm happy to put together a PR once the 5.2 release is out. 

### Context

- Wagtail is a popular CMS built with Django, it's more of a framework to build a CMS with developer extensibility in mind. https://github.com/wagtail/wagtail & https://wagtail.org/
- Last year, Wagtail started to adopt Stimulus for internal admin JavaScript interactions, replacing a mix of jQuery, ad-hoc JS and as a way to move away from inline scripts. A parallel goal is to fully support CSP within the admin interface. 
- The upcoming release (November 2023) of Wagtail starts our support for developers **using** Wagtail to build their own Stimulus controllers with the globals and documentation we provide.
  - Release notes - https://docs.wagtail.org/en/latest/releases/5.2.html#support-extending-wagtail-client-side-with-stimulus
  - You can see the future docs here https://docs.wagtail.org/en/latest/extending/extending_client_side.html#extending-with-stimulus
- See also https://discuss.hotwired.dev/t/wagtail-django-cms-rfc-to-adopt-stimulus/4197

**Comment by marcoroth** [comment]
Hey @lb-, thanks for proposing to add Wagtail! 

I think Wagtail most definitely should be featured on the website, feel free to open a PR now or after you released 5.2 🙌🏼

**Comment by lb-** [comment]
Thank you, I will do this once our 5.2 is live.
